### ISSUE TITLE
line.thrift is missing

### ISSUE THREAD

**Issue by teddyhartanto** [ruyaoyao/LineAPI4J#15]
Hi, I cloned the project and used "mvn package" as per instruction. When I built the project, there are errors. One of them is that there's no 'line.thrift' package. I saw in your code that you tried to import from line.thrift.AuthQrcode, etc. How do I solve this issue? Thank you so much.

**Comment by TeddyHartanto** [comment]
Details as follow (produced after I ran 'mvn package'):

[INFO] 100 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.133 s
[INFO] Finished at: 2016-06-26T16:13:01+08:00
[INFO] Final Memory: 14M/147M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project LineAPI4J: Compilation failure: Compilation failure
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineGroup.java:[38,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineGroup.java:[39,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineBase.java:[45,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineBase.java:[46,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineBase.java:[47,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineBase.java:[48,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineGroup.java:[51,3] cannot find symbol
[ERROR] symbol:   class Group
[ERROR] location: class io.cslinmiso.line.model.LineGroup
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineContact.java:[40,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[44,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[45,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[46,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[47,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[48,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[49,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[50,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[51,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[52,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[53,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[54,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[55,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[56,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[57,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineGroup.java:[61,39] cannot find symbol
[ERROR] symbol:   class Group
[ERROR] location: class io.cslinmiso.line.model.LineGroup
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineGroup.java:[149,10] cannot find symbol
[ERROR] symbol:   class Group
[ERROR] location: class io.cslinmiso.line.model.LineGroup
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineGroup.java:[153,24] cannot find symbol
[ERROR] symbol:   class Group
[ERROR] location: class io.cslinmiso.line.model.LineGroup
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineBase.java:[81,50] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: class io.cslinmiso.line.model.LineBase
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineBase.java:[116,34] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: class io.cslinmiso.line.model.LineBase
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineMessage.java:[34,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineMessage.java:[41,34] cannot find symbol
[ERROR] symbol: class Message
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineContact.java:[54,3] cannot find symbol
[ERROR] symbol:   class Contact
[ERROR] location: class io.cslinmiso.line.model.LineContact
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineRoom.java:[38,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineRoom.java:[39,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineRoom.java:[40,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineContact.java:[79,41] cannot find symbol
[ERROR] symbol:   class Contact
[ERROR] location: class io.cslinmiso.line.model.LineContact
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineContact.java:[109,10] cannot find symbol
[ERROR] symbol:   class Contact
[ERROR] location: class io.cslinmiso.line.model.LineContact
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineContact.java:[118,26] cannot find symbol
[ERROR] symbol:   class Contact
[ERROR] location: class io.cslinmiso.line.model.LineContact
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineContact.java:[218,21] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineContact.java:[222,21] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineContact.java:[226,21] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[39,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[40,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[41,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[42,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[43,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[44,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[45,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[46,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[47,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[48,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[49,19] package line.thrift does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[50,31] package line.thrift.TalkService does not exist
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[74,3] cannot find symbol
[ERROR] symbol:   class Profile
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[150,49] cannot find symbol
[ERROR] symbol:   class Contact
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[226,10] cannot find symbol
[ERROR] symbol:   class Profile
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[293,62] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[305,40] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[335,43] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[360,77] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[377,14] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[488,62] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[501,77] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[533,80] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[551,50] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[570,10] cannot find symbol
[ERROR] symbol:   class Message
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[570,67] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[589,10] cannot find symbol
[ERROR] symbol:   class TMessageBox
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[604,46] cannot find symbol
[ERROR] symbol:   class TMessageBox
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[605,14] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[620,33] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[625,42] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[737,51] cannot find symbol
[ERROR] symbol:   class Message
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[747,59] cannot find symbol
[ERROR] symbol:   class Message
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineClient.java:[818,26] cannot find symbol
[ERROR] symbol:   class Profile
[ERROR] location: class io.cslinmiso.line.model.LineClient
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineMessage.java:[44,11] cannot find symbol
[ERROR] symbol:   class Message
[ERROR] location: class io.cslinmiso.line.model.LineMessage
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineMessage.java:[56,41] cannot find symbol
[ERROR] symbol:   class Message
[ERROR] location: class io.cslinmiso.line.model.LineMessage
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineMessage.java:[93,10] cannot find symbol
[ERROR] symbol:   class Message
[ERROR] location: class io.cslinmiso.line.model.LineMessage
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineMessage.java:[97,26] cannot find symbol
[ERROR] symbol:   class Message
[ERROR] location: class io.cslinmiso.line.model.LineMessage
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineRoom.java:[52,3] cannot find symbol
[ERROR] symbol:   class Room
[ERROR] location: class io.cslinmiso.line.model.LineRoom
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineRoom.java:[57,38] cannot find symbol
[ERROR] symbol:   class Room
[ERROR] location: class io.cslinmiso.line.model.LineRoom
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineRoom.java:[76,33] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: class io.cslinmiso.line.model.LineRoom
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineRoom.java:[81,50] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: class io.cslinmiso.line.model.LineRoom
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineRoom.java:[103,10] cannot find symbol
[ERROR] symbol:   class Room
[ERROR] location: class io.cslinmiso.line.model.LineRoom
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/model/LineRoom.java:[107,23] cannot find symbol
[ERROR] symbol:   class Room
[ERROR] location: class io.cslinmiso.line.model.LineRoom
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[123,3] cannot find symbol
[ERROR] symbol:   class Client
[ERROR] location: interface io.cslinmiso.line.api.LineApi
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[125,3] cannot find symbol
[ERROR] symbol:   class LoginResult
[ERROR] location: interface io.cslinmiso.line.api.LineApi
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[127,3] cannot find symbol
[ERROR] symbol:   class LoginResult
[ERROR] location: interface io.cslinmiso.line.api.LineApi
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[143,3] cannot find symbol
[ERROR] symbol:   class AuthQrcode
[ERROR] location: interface io.cslinmiso.line.api.LineApi
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[166,3] cannot find symbol
[ERROR] symbol:   class Contact
[ERROR] location: interface io.cslinmiso.line.api.LineApi
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[166,53] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: interface io.cslinmiso.line.api.LineApi
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[173,15] cannot find symbol
[ERROR] symbol:   class Contact
[ERROR] location: interface io.cslinmiso.line.api.LineApi
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[173,85] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: interface io.cslinmiso.line.api.LineApi
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[181,22] cannot find symbol
[ERROR] symbol:   class Contact
[ERROR] location: interface io.cslinmiso.line.api.LineApi
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[181,78] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: interface io.cslinmiso.line.api.LineApi
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[189,15] cannot find symbol
[ERROR] symbol:   class Contact
[ERROR] location: interface io.cslinmiso.line.api.LineApi
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[190,14] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: interface io.cslinmiso.line.api.LineApi
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[197,22] cannot find symbol
[ERROR] symbol:   class Contact
[ERROR] location: interface io.cslinmiso.line.api.LineApi
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[197,78] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: interface io.cslinmiso.line.api.LineApi
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[205,15] cannot find symbol
[ERROR] symbol:   class Contact
[ERROR] location: interface io.cslinmiso.line.api.LineApi
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[206,14] cannot find symbol
[ERROR] symbol:   class TalkException
[ERROR] location: interface io.cslinmiso.line.api.LineApi
[ERROR] /C:/Users/user/Documents/GitHub/LineAPI4J/src/main/java/io/cslinmiso/line/api/LineApi.java:[213,3] cannot find symbol
[ERROR] symbol:   class Profile
[ERROR] location: interface io.cslinmiso.line.api.LineApi
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by cslinmiso** [comment]
Hi TeddyHartanto,
The library is in 'lib' folder, would you please check the build path? 
See if you actually include the library in your project.

Thanks!

**Comment by royl2k90** [comment]
I did a git clone, then cd to the project folder, and type 'mvn package'. It says build failure and package line.thrift is missing. I get the same error as the above. The thrift-line-talkservice.jar file is in the lib folder.

**Comment by cslinmiso** [comment]
I see what's going on here.
 I've made some changes, please try again. I've too busy to test it but fingers crossed.

**Comment by royl2k90** [comment]
```
C:\Users\RoyLin>git clone git://github.com/cslinmiso/LineAPI4J.git
Cloning into 'LineAPI4J'...
remote: Counting objects: 271, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 271 (delta 5), reused 0 (delta 0), pack-reused 259Receiving objects:  75% (204/271), 5.59 MiB | 231.00 KiBReceiving objects: 100% (271/271), 5.79 MiB | 240.00 KiB/s, done.

Resolving deltas: 100% (94/94), done.
Checking connectivity... done.

C:\Users\RoyLin>cd LineAPI4J

C:\Users\RoyLin\LineAPI4J>mvn package
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM C:\Users\RoyLin\LineAPI4J\pom.xml: Unrecognised tag: 'dependencies' (position: START_TAG seen ...<dependencies>\r\n\t\t<dependencies>... @18:17)  @ line 18, column 17
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project  (C:\Users\RoyLin\LineAPI4J\pom.xml) has 1 error
[ERROR]     Non-parseable POM C:\Users\RoyLin\LineAPI4J\pom.xml: Unrecognised tag: 'dependencies' (position: START_TAG seen ...<dependencies>\r\n\t\t<dependencies>... @18:17)  @ line 18, column 17 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
```

**Comment by TeddyHartanto** [comment]
Hi royl2k90, Just remove one of the duplicate <dependencies> tag. And then it'll work.

Hi cslinmiso, thanks a lot for providing this API! It works except for a minor bug pointed out by royl2k90 - there's a duplicate <dependencies> tag in the pom.xml. I tried the API last night and I'm very satisfied. Thank you again! :-)

**Comment by TeddyHartanto** [comment]
Duplicate \<dependencies\> tag*

**Comment by royl2k90** [comment]
Some warnings in the Maven build. Not encouraged to use system paths. Try shipping the JAR as a separate artifact. mvn compile would automatically download the dependencies for us.

```
C:\Users\RoyLin\LineAPI4J>mvn package
[INFO] Scanning for projects...
**[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.cslinmiso:LineAPI4J:jar:0.5
[WARNING] 'dependencies.dependency.systemPath' for line.thrift.:thrift-line-talkservice:jar should not point at files within the project directory, ${basedir}/lib/thrift-line-talkservice.jar will be unresolvable by dependent projects @ line 23, column 16
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
NG] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]**
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building LineAPI4J 0.5
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ LineAPI4J ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\RoyLin\LineAPI4J\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ LineAPI4J ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 10 source files to C:\Users\RoyLin\LineAPI4J\target\classes
[WARNING] /C:/Users/RoyLin/LineAPI4J/src/main/java/io/cslinmiso/line/utils/Utility.java: C:\Users\RoyLin\LineAPI4J\src\main\java\io\cslinmiso\line\utils\Utility.java uses or overrides a deprecated API.
[WARNING] /C:/Users/RoyLin/LineAPI4J/src/main/java/io/cslinmiso/line/utils/Utility.java: Recompile with -Xlint:deprecation for details.
[WARNING] /C:/Users/RoyLin/LineAPI4J/src/main/java/io/cslinmiso/line/utils/Utility.java: Some input files use unchecked or unsafe operations.
[WARNING] /C:/Users/RoyLin/LineAPI4J/src/main/java/io/cslinmiso/line/utils/Utility.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ LineAPI4J ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\RoyLin\LineAPI4J\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ LineAPI4J ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to C:\Users\RoyLin\LineAPI4J\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ LineAPI4J ---
[INFO] Surefire report directory: C:\Users\RoyLin\LineAPI4J\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.cslinmiso.LineAPI4J.AppTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.069 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ LineAPI4J ---
[INFO] Building jar: C:\Users\RoyLin\LineAPI4J\target\LineAPI4J-0.5.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.500 s
[INFO] Finished at: 2016-06-28T10:22:40+08:00
[INFO] Final Memory: 21M/357M
[INFO] ------------------------------------------------------------------------
```

**Comment by royl2k90** [comment]
What is the next step after successful build? How do I run it and send a message to my LINE contact via console? Do I have to login via email and password or authentication token?

**Comment by cslinmiso** [comment]
@royl2k90 
This very API run on Java, you could check [Demo code](https://github.com/cslinmiso/LineAPI4J/blob/master/src/main/java/io/cslinmiso/LineAPI4J/App.java) for more information.
Include the jar in your project and initialize it with your account and password.

**Comment by cslinmiso** [comment]
@TeddyHartanto 
There are still so many problems with this API.
LINE has been updated their protocol a while ago, please do not be panic if you can't read the message text while long polling. 
This problem still remain unsolved for now, see the thread. [issue](https://github.com/carpedm20/LINE/issues/71)

**Comment by teddyhartanto** [comment]
@ruyaoyao
Yep, noticed that. It's quite bothersome, but I can still send stickers/messages to my friends. Overall I think it's a success :smile:

**Comment by royl2k90** [comment]
When I import the project into Eclipse and add external JAR file thrift-line-talkservice.jar, there were errors. I am unable to build the project in Netbeans either. How did you do it step by step? @TeddyHartanto

**Comment by TeddyHartanto** [comment]
@royl2k90 I just use the cmd prompt. I didn't use Eclipse to build (didn't know how to :stuck_out_tongue: )
1. git clone <URL>
2. cd <project_dir>
3. remove the extra <dependencies> tag
4. mvn package

**Comment by royl2k90** [comment]
What is next after mvn package? How do you send a message to your friends using cmd?

**Comment by cslinmiso** [comment]
I am not sure how well you understand the meaning of the commend 'mvn package'.
It packaged LineAPI4J as a JAR file which you have to include to build path of your own project.
As previous comment, you could check [Demo code](https://github.com/cslinmiso/LineAPI4J/blob/master/src/main/java/io/cslinmiso/LineAPI4J/App.java) for more information.

**Comment by flyingstarlai** [comment]
i clone the latest version but still cant read recent messages... any idea?

**Comment by FrancisAiknow** [comment]
> Duplicate tag*

Can you specify which tag?
